force-app/main/default/objects/Opportunity/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Important</fullName>
            </value>
            <value>
                <fullName>Very Important</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Priority_Transition__c.field-meta.xml
<CustomField>
    <fullName>Priority_Transition__c</fullName>
    <label>Priority Transition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Important</fullName>
            </value>
            <value>
                <fullName>Very Important</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityHandler.cls
/**
 * Created by Steffen Naundorf on 31.05.2021.
 */

public without sharing class OpportunityHandler extends TriggerHandlerExtension {
  // Constructor
  public OpportunityHandler() {
    super();
  }

  //public override void bulkBefore() { }

  //public override void bulkAfter() {}

  //public override void beforeInsert(SObject obj) { addToLoopCount(); }

  public override void beforeUpdate(SObject oldObj, SObject obj) {
    addToLoopCount();
    Opportunity opportunityNew = (Opportunity) obj;

    if (
      opportunityNew.Priority_Transition__c == 'Important' ||
      opportunityNew.Priority_Transition__c == 'Very Important'
    ) {
    } else {
      opportunityNew.Priority__c = opportunityNew.Priority_Transition__c;
    }
  }

  //public override void beforeDelete(SObject obj) { addToLoopCount();}

  //public override void afterInsert(SObject obj) { addToLoopCount(); }

  //public override void afterUpdate(SObject oldObj, SObject obj) { addToLoopCount(); }

  //public override void afterDelete(SObject obj) { addToLoopCount();}

  //public override void andFinally() { }
}